name: Release

on:
  push:
    branches:
      - main

permissions: {}
jobs:
  release:
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)

    name: ${{ matrix.channel }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        channel:
          - latest
          - dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: pnpm
          registry-url: https://registry.npmjs.org
          key: node18

      - name: Install dependencies
        run: pnpm

      - name: Prepare release
        run: pnpm prerelease

      # https://github.com/changesets/action
      - name: Create release pull request or Publish to npm
        if: matrix.channel == 'latest'
        uses: changesets/action@v1
        with:
          # defined in package.json#scripts
          version: pnpm changesetversion
          publish: pnpm changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # https://github.com/atlassian/changesets/blob/master/docs/snapshot-releases.md
      - name: Release to @dev channel
        if: matrix.channel == 'dev'
        run: |
          pnpm changeset version --snapshot
          pnpm changeset publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
